FROM node:22.4.1-slim as build

ENV VITE_SOME_KEY="321"

# RUN apk add git
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM alpine:3.18
RUN npm install -g http-server
COPY --from=build /workspace/build.zip ./    

# EXPOSE 8080

# CMD ["http-server", "-p", "8080"]